config/routes.rb
Mconf::Application.routes.draw do

  controllers = { :sessions => "sessions", :registrations => "registrations" }
  paths = { :sign_in => "login", :sign_out => "logout", :sign_up => "signup" }
  devise_for :users, :path_names => paths, :controllers => controllers
  devise_scope :user do
    get "login", :to => "sessions#new"
    get "logout", :to => "sessions#destroy"
    get "register", :to => "registrations#new"
  end

  bigbluebutton_routes :default, :controllers => { :servers => 'custom_bigbluebutton_servers', :rooms => 'custom_bigbluebutton_rooms' }

  match '/webconf/:id', :to => 'custom_bigbluebutton_rooms#invite',
                        :as => "join_webconf"

  match '/secure', :to => 'shibboleth#create', :as => "shibboleth"
  match '/secure/info', :to => 'shibboleth#info', :as => "shibboleth_info"

  resources :logos do
    collection do
      post :new
    end
  end

  resources :machines do
    collection do
      get :contact_mail
      get :my_mailer
    end
  end

  resources :spaces do

    bigbluebutton_routes :room_matchers

    member do
      post :enable
      post :leave
    end

    resources :users do
      resource :profile, :except => [:new, :create]
    end

    resource :webconference
    resources :readers

    resources :events do

      member do
        post :spam
        get :spam_lightbox
      end

      collection do
        get :add_time
        get :copy_next_week
        get :remove_time
      end

      resources :invitations
      resources :participants

      resource :logo, :controller => 'event_logos' do
        member do
          post :precrop
        end
      end
    end

    resources :posts do
      member do
        get :reply_post
        post :spam
        get :spam_lightbox
      end
    end

    delete 'attachments', :to => 'attachments#delete_collection', :as => 'attachments'

    resources :attachments do
      member do
        get :edit_tags
      end
    end

    resources :entries
    resource :logo do
      member do
        post :new
        post :precrop
      end
    end

    resources :admissions
    resources :invitations
    resources :join_requests
    resources :news
  end

  resources :invitations do
    member do
      get :accept
    end
  end

  resources :permissions
  resources :admissions
  resources :memberships

  resources :users do
    get :fellows, :on => :collection, :defaults => { :format => 'json' }
    get :select_users, :on => :collection
    get :current, :on => :collection, :defaults => { :format => 'xml' }
    member do
      post :enable
      get :edit_bbb_room
    end

    resources :private_messages, :as => 'messages', :except => [:edit]
    resource :profile, :except => [:new, :create] do
      resource :logo
    end
    resource :avatar do
      member do
        post :precrop
      end
    end
  end

  resource :home do
    member do
      get :user_rooms
    end
  end

  resource :invite do
    member do
      get :invite_room, :as => 'inviteroom'
      post :send_invite, :as => 'sendinvite'
      get :send_notification, :as => 'sendnotification'
    end
  end

  resources :feedback do
    collection do
      get :webconf
    end
  end

  resource :site, :only => [:show, :edit, :update]

  match '/manage/users', :to => 'manage#users', :as => 'manage_users'
  match '/manage/spaces', :to => 'manage#spaces', :as => 'manage_spaces'
  match '/manage/spam', :to => 'manage#spam', :as => 'manage_spam'

  resource :session_locale
  match ':locale/:controller/:action/:id'
  match 'locale/set/:id', :to => 'locale#set', :as => 'set'

  root :to => 'frontpage#show'

  match 'help', :to => 'faq#show', :as => 'help'
  match 'faq', :to => 'faq#show', :as => 'faq'

  match '/statistics', :to => 'statistics#show', :as => 'show_statistics'

  match '/reset_password/:reset_password_code', :to => 'users#reset_password', :as => 'reset_password'

  match 'get_file/:id', :to => 'machines#get_file', :as => 'get_file'

  unless Rails.application.config.consider_all_requests_local
    match '*not_found', :to => 'errors#error_404'
  end
end

app/views/search/_articles.html.erb
<h2 class="title separador"> Posts</h2>

<div class="contenido_search">
	
	<br/>
		<%if @posts == []%>
	     	<p class="red">No posts found</p>
	    <%else%> 
			<%if @posts.size == 1%>	   
	     		<h3 class="red">1 post was found</h3>
		 		<br/>
	     		<% @posts.each do |post| %>
	       			<%if post%>
	         			<%=show_post(post,@space,"edit","destroy")%> 
	       			<%end%>
         		<%end%>
	   		<%else%>
         		<h3 class="red"><%=@posts.size%> post was found</h3>
		 		<br/>	
	     		<% @posts.each do |post| %>
	       			<%if post%>
	         			<%=show_post(post,@space,"edit","destroy")%> 
	       			<%end%>
         		<%end%>
			<%end%>
		<%end%>	
</div>

app/views/search/_space.html.erb
<div class="single_space">
	<%=image_tag(logo_image_path(space, :size =>'h48'), :align => "left")%>
  <p><%=link_to highlight(sanitize(space.name),params[:query]),space_path(space), :class => "space_title" %></p>
  <p><%=highlight(sanitize(space.description), params[:query])%></p>
</div>

app/views/search/_video.html.erb
<div class="single_event">
  <p><%=link_to truncate(entry.title, 32),space_event_path(entry.event.space, entry.event, :show_video => entry.id), :class => "video_title" %></p>
  <ul>
  	<li class="main_text">
        <%= t('event.one')%>:<span class="unified_event"><%=link_to sanitize(highlight(entry.event.title,params[:query])), space_event_path(entry.event.space, entry.event),:class=>"unified_event"%></span>
    </li>
		<li class="main_text">
        <%= t('agenda.entry.speakers')%>: <span class="unified_user"><%=highlight(entry_speakers(entry), params[:query])%></span>
    </li>
    <li class="main_text">
        <%= t('description')%>: <span> <%=highlight(entry.description,params[:query])%></span>
    </li>
	</ul>
</div>