config/routes.rb
Mconf::Application.routes.draw do

  controllers = { :sessions => "sessions", :registrations => "registrations" }
  paths = { :sign_in => "login", :sign_out => "logout", :sign_up => "signup" }
  devise_for :users, :path_names => paths, :controllers => controllers
  devise_scope :user do
    get "login", :to => "sessions#new"
    get "logout", :to => "sessions#destroy"
    get "register", :to => "registrations#new"
  end

  bigbluebutton_routes :default, :controllers => { :servers => 'custom_bigbluebutton_servers', :rooms => 'custom_bigbluebutton_rooms' }

  match '/webconf/:id', :to => 'custom_bigbluebutton_rooms#invite',
                        :as => "join_webconf"

  match '/secure', :to => 'shibboleth#create', :as => "shibboleth"
  match '/secure/info', :to => 'shibboleth#info', :as => "shibboleth_info"

  resources :logos do
    collection do
      post :new
    end
  end

  resources :machines do
    collection do
      get :contact_mail
      get :my_mailer
    end
  end

  resources :spaces do

    bigbluebutton_routes :room_matchers

    member do
      post :enable
      post :leave
    end

    resources :users do
      resource :profile, :except => [:new, :create]
    end

    resource :webconference
    resources :readers

    resources :events do

      member do
        post :spam
        get :spam_lightbox
      end

      collection do
        get :add_time
        get :copy_next_week
        get :remove_time
      end

      resources :invitations
      resources :participants

      resource :logo, :controller => 'event_logos' do
        member do
          post :precrop
        end
      end
    end

    resources :posts do
      member do
        get :reply_post
        post :spam
        get :spam_lightbox
      end
    end

    delete 'attachments', :to => 'attachments#delete_collection', :as => 'attachments'

    resources :attachments do
      member do
        get :edit_tags
      end
    end

    resources :entries
    resource :logo do
      member do
        post :new
        post :precrop
      end
    end

    resources :admissions
    resources :invitations
    resources :join_requests
    resources :news
  end

  resources :invitations do
    member do
      get :accept
    end
  end

  resources :permissions
  resources :admissions
  resources :memberships

  resources :users do
    get :fellows, :on => :collection, :defaults => { :format => 'json' }
    get :select_users, :on => :collection
    get :current, :on => :collection, :defaults => { :format => 'xml' }
    member do
      post :enable
      get :edit_bbb_room
    end

    resources :private_messages, :as => 'messages', :except => [:edit]
    resource :profile, :except => [:new, :create] do
      resource :logo
    end
    resource :avatar do
      member do
        post :precrop
      end
    end
  end

  resource :home do
    member do
      get :user_rooms
    end
  end

  resource :invite do
    member do
      get :invite_room, :as => 'inviteroom'
      post :send_invite, :as => 'sendinvite'
      get :send_notification, :as => 'sendnotification'
    end
  end

  resources :feedback do
    collection do
      get :webconf
    end
  end

  resource :site, :only => [:show, :edit, :update]

  match '/manage/users', :to => 'manage#users', :as => 'manage_users'
  match '/manage/spaces', :to => 'manage#spaces', :as => 'manage_spaces'
  match '/manage/spam', :to => 'manage#spam', :as => 'manage_spam'

  resource :session_locale
  match ':locale/:controller/:action/:id'
  match 'locale/set/:id', :to => 'locale#set', :as => 'set'

  root :to => 'frontpage#show'

  match 'help', :to => 'faq#show', :as => 'help'
  match 'faq', :to => 'faq#show', :as => 'faq'

  match '/statistics', :to => 'statistics#show', :as => 'show_statistics'

  match '/reset_password/:reset_password_code', :to => 'users#reset_password', :as => 'reset_password'

  match 'get_file/:id', :to => 'machines#get_file', :as => 'get_file'

  unless Rails.application.config.consider_all_requests_local
    match '*not_found', :to => 'errors#error_404'
  end
end

app/views/notifier/activation.html.erb
<html>
<body>

<%= t('email.account_activated', :sitename => @sitename)%><br/><br/>

<%= raw(t('email.url_activated', :name => @user.email, :url => "http://" + Site.current.domain.to_s + "/")) %><br/><br/>

<%= @signature %><br/>
</body>
</html>

app/views/notifier/contact_mail_html.html.erb
<html>
<body>

<h3><%= t('hello') %></h3>
     
    <p>
		<%= t('received_message_more_machines', :user => @mail_info["from_name"]) %>
    </p>
     
    <br/>
    <%= t('his_message_reads_thus') %>:
	
    <br/>
   <p>
   <%= @mail_info["message"] %>
   <p>
   <%= t('consider_and_reply') %></p>
   <p><%= t('user.vcc_email', :dir => @mail_info["user_email"]) %></p> 
   <p><%= t('email.used_from'), :dir => @mail_info["from_email"]) %></p> 
   <br/>
</body>
</html>

app/views/notifier/digest_email.html.erb
<html>
  <body>
    <h3><%= t('email.digest.message') %></h3>
    <% unless @inbox.empty? %>
      <h4><%= t('private_message.title', :count => @inbox.size) %></h4>
      <% @inbox.take(10).each do |inbox| %>
        <p>
          <%= t('email.digest.inbox', :sender_name => inbox.sender.name).html_safe %> <%= link_to sanitize(inbox.title), user_message_url(inbox.receiver, inbox) %>
          <%= t('updated_time_ago', :time => sanitize(time_ago_in_words(inbox.updated_at))) %>
        </p>
      <% end %>
      <% if @inbox.size > 10 %>
        <p><%= t('private_message.more', :count => @inbox.size - 10) %></p>
      <% end %>
    <% end %>
    <% unless @posts.empty? %>
      <h4><%= t('post.title', :count => @posts.size) %></h4>
      <% @posts.take(10).each do |post| %>
        <p>
          <%= t('email.digest.posted', :author_name => post.author.name, :space_name => post.space.name).html_safe %> <%=link_to post.title, space_post_url(post.space,post)%>
          <%= t('updated_time_ago', :time => time_ago_in_words(post.updated_at)) %>
        </p>
      <% end %>
      <% if @posts.size > 10 %>
        <p><%= t('post.more', :count => @posts.size - 10) %></p>
      <% end %>
    <% end %>
    <% unless @news.empty? %>
      <h4><%= t('news.title', :count => @news.size) %></h4>
      <% @news.take(10).each do |news| %>
        <p>
          <%= t('email.digest.news', :space_name => news.space.name).html_safe %> <%= link_to(sanitize(news.title), space_url(news.space)) %>
          <%= t('updated_time_ago', :time => time_ago_in_words(news.updated_at)) %><br/>
        </p>
      <% end %>
      <% if @news.size > 10 %>
        <p><%= t('new.more', :count => @news.size - 10) %></p>
      <% end %>
    <% end %>
    <% unless @attachments.empty? %>
      <h4><%= t('attachment.title', :count => @attachments.size) %></h4>
      <% @attachments.take(10).each do |att| %>
        <p>
          <%= t('email.digest.attachment', :author_name => att.author.name, :space_name => att.space.name).html_safe %> <%= link_to(sanitize(att.filename), space_attachment_url(att.space, att, :format => att.format!)) %>
          <%= t('created_time_ago', :time => sanitize(time_ago_in_words(att.created_at))) %>
        </p>
      <% end %>
      <% if @attachments.size > 10 %>
        <p><%= t('attachment.more', :count => @attachments.size - 10) %></p>
      <% end %>
    <% end %>
    <% unless @events.empty? %>
      <h4><%= t('event.title', :count => @events.size) %></h4>
      <% @events.take(10).each do |event| %>
        <p>
          <%= t('email.digest.event', :author_name => event.author.name, :space_name => event.space.name).html_safe %> <%=link_to sanitize(event.title), space_event_url(event.space, event) %>
          <%= t('updated_time_ago', :time => sanitize(time_ago_in_words(event.updated_at))) %>
        </p>
      <% end %>
      <% if @events.size > 10 %>
        <p><%= t('event.more', :count => @events.size - 10) %></p>
      <% end %>
    <% end %>
    <%= @signature %>
  </body>
</html>

app/views/notifier/event_group_invitation_email.html.erb
<html>
  <body>
      <%=@event.group_invitation_msg%><br/><br/>
  </body>
</html>

app/views/notifier/event_notification_email.html.erb
<html>
  <body>
    <%=
      t('event.notification_message',
       :name => @receiver.full_name,
       :event_name => @event.name,
       :space => @event.space.name,
       :event_date => @event.start_date.strftime("%A %B %d at %H:%M:%S"),
       :event_url => space_event_url(@event.space,@event),
       :username => @sender.full_name,
       :useremail => @sender.email,
       :userorg => @sender.organization
      ).html_safe
    %>
  </body>
</html>

app/views/notifier/feedback_email.html.erb
<html>
<body>
<%= t('feedback.email', :email => @user) %><br/><br/>

<%=@text%><br/>

</body>
</html>

app/views/notifier/forgot_password.html.erb
<%= @name %>, please follow the link to reset your password

<%= @url %>

app/views/notifier/invitation_email.html.erb
<html>
  <body>
    <p><%= @name + "," %></p>
    <%= t('invitation.full_message', 
        :username => @user.full_name, 
        :space => @space.name, 
        :comment => @invitation.comment, 
        :url => invitation_url(@invitation), 
        :space_url => space_url(@space), 
        :user_name => @user.full_name, 
        :user_email => @user.email, 
        :user_organization => @user.organization, 
        :contact => Site.current.smtp_sender, 
        :feedback => new_feedback_url()
        ).html_safe
    %>
    <br/><br/>
  </body>
</html>

app/views/notifier/performance_update_notification_email.html.erb
<html>
  <body>
  	  <%= @text %>
  	  <br/><br/>
  </body>
</html>

app/views/notifier/performance_update_notification_email.text.html.erb
<html>
  <body>
  	  <%= @text %>
  	  <br/><br/>
  </body>
</html>

app/views/notifier/processed_join_request_email.html.erb
<html>
<body>
<%= t('email.invitation_result.user_side', :action => @action, :spacename =>@space.name)%><br/><br/>	

<%if @jr.accepted?%>
  <%= raw(t('invitation.access_space', :spacename => @space.name, :space_url => space_url(@space, :host => Site.current.domain))) %><br/><br/>
<%else%>
  <%= raw(t('invitation.rejoin_space', :space_url => new_space_join_request_url(@space, :host => Site.current.domain))) %><br/><br/>
<%end%>

<%= t('admin.space', :spacename => @space.name)%>

</body>
</html>

app/views/notifier/reset_password.html.erb
<html>
<body>

<%= t('password.reset_email', :sitename=> @sitename)%>.<br/><br/>

<%= @signature %><br/>

</body>
</html>

app/views/notifier/reset_password.text.html.erb
<html>
<body>

<%= t('password.reset_email', :sitename=> @sitename)%>.<br/><br/>

<%= @signature %><br/>

</body>
</html>

app/views/notifier/spam_email.html.erb
<html>
<body>
<%= t('spam.reported', :name => @user, :sitename => @sitename)%>.<br/><br/>


<%=@text%><br/><br/>

<%= @signature %><br/>

</body>
</html>