config/routes.rb
Mconf::Application.routes.draw do

  controllers = { :sessions => "sessions", :registrations => "registrations" }
  paths = { :sign_in => "login", :sign_out => "logout", :sign_up => "signup" }
  devise_for :users, :path_names => paths, :controllers => controllers
  devise_scope :user do
    get "login", :to => "sessions#new"
    get "logout", :to => "sessions#destroy"
    get "register", :to => "registrations#new"
  end

  bigbluebutton_routes :default, :controllers => { :servers => 'custom_bigbluebutton_servers', :rooms => 'custom_bigbluebutton_rooms' }

  match '/webconf/:id', :to => 'custom_bigbluebutton_rooms#invite',
                        :as => "join_webconf"

  match '/secure', :to => 'shibboleth#create', :as => "shibboleth"
  match '/secure/info', :to => 'shibboleth#info', :as => "shibboleth_info"

  resources :logos do
    collection do
      post :new
    end
  end

  resources :machines do
    collection do
      get :contact_mail
      get :my_mailer
    end
  end

  resources :spaces do

    bigbluebutton_routes :room_matchers

    member do
      post :enable
      post :leave
    end

    resources :users do
      resource :profile, :except => [:new, :create]
    end

    resource :webconference
    resources :readers

    resources :events do

      member do
        post :spam
        get :spam_lightbox
      end

      collection do
        get :add_time
        get :copy_next_week
        get :remove_time
      end

      resources :invitations
      resources :participants

      resource :logo, :controller => 'event_logos' do
        member do
          post :precrop
        end
      end
    end

    resources :posts do
      member do
        get :reply_post
        post :spam
        get :spam_lightbox
      end
    end

    delete 'attachments', :to => 'attachments#delete_collection', :as => 'attachments'

    resources :attachments do
      member do
        get :edit_tags
      end
    end

    resources :entries
    resource :logo do
      member do
        post :new
        post :precrop
      end
    end

    resources :admissions
    resources :invitations
    resources :join_requests
    resources :news
  end

  resources :invitations do
    member do
      get :accept
    end
  end

  resources :permissions
  resources :admissions
  resources :memberships

  resources :users do
    get :fellows, :on => :collection, :defaults => { :format => 'json' }
    get :select_users, :on => :collection
    get :current, :on => :collection, :defaults => { :format => 'xml' }
    member do
      post :enable
      get :edit_bbb_room
    end

    resources :private_messages, :as => 'messages', :except => [:edit]
    resource :profile, :except => [:new, :create] do
      resource :logo
    end
    resource :avatar do
      member do
        post :precrop
      end
    end
  end

  resource :home do
    member do
      get :user_rooms
    end
  end

  resource :invite do
    member do
      get :invite_room, :as => 'inviteroom'
      post :send_invite, :as => 'sendinvite'
      get :send_notification, :as => 'sendnotification'
    end
  end

  resources :feedback do
    collection do
      get :webconf
    end
  end

  resource :site, :only => [:show, :edit, :update]

  match '/manage/users', :to => 'manage#users', :as => 'manage_users'
  match '/manage/spaces', :to => 'manage#spaces', :as => 'manage_spaces'
  match '/manage/spam', :to => 'manage#spam', :as => 'manage_spam'

  resource :session_locale
  match ':locale/:controller/:action/:id'
  match 'locale/set/:id', :to => 'locale#set', :as => 'set'

  root :to => 'frontpage#show'

  match 'help', :to => 'faq#show', :as => 'help'
  match 'faq', :to => 'faq#show', :as => 'faq'

  match '/statistics', :to => 'statistics#show', :as => 'show_statistics'

  match '/reset_password/:reset_password_code', :to => 'users#reset_password', :as => 'reset_password'

  match 'get_file/:id', :to => 'machines#get_file', :as => 'get_file'

  unless Rails.application.config.consider_all_requests_local
    match '*not_found', :to => 'errors#error_404'
  end
end

app/models/post.rb
# -*- coding: utf-8 -*-
# This file is part of Mconf-Web, a web application that provides access
# to the Mconf webconferencing system. Copyright (C) 2010-2012 Mconf
#
# This file is licensed under the Affero General Public License version
# 3 or later. See the LICENSE file.

class Post < ActiveRecord::Base
  belongs_to :space
  belongs_to :author, :polymorphic => true
  has_many :post_attachments, :dependent => :destroy
  has_many :attachments, :through => :post_attachments

  belongs_to :event

  accepts_nested_attributes_for :attachments, :allow_destroy => true

  acts_as_resource :per_page => 10
  acts_as_content :reflection => :space
  acts_as_taggable
  #TODO Rails 3. Conflicts with station inquirer ("ORDER BY clause should come after UNION not before: SELECT  * FROM")
  acts_as_tree #:order => 'updated_at ASC'

  scope :public, lambda { |arg|
    join(:space).where('public = ?', true)
  }
  scope :not_events, lambda {
    where(:event_id =>  nil)
  }

  validates_presence_of :title, :unless => Proc.new { |post| post.parent.present? || post.event.present? }
  validates_presence_of :text, :if => Proc.new { |post| post.attachments.empty? && post.event.blank? }

  # Fill attachments author and space
  before_validation do |post|
    post.attachments.each do |a|
      a.space  ||= post.space
      a.author = post.author
    end
  end

  # Update parent Posts when commenting to it
  after_save do |post|
    post.parent.try(:touch)
  end

  def author
    case author_type
    when User
      User.find_with_disabled(author_id)
    when NilClass
      nil
    else
      author_type.constantize.find_by_id author_id
    end
  end

  def space
    space_id.present? ?
      Space.find_with_disabled(space_id) :
      nil
  end

  # This method return the 3 last comment of a thread if the thread has more than 3 comments.
  # If not, return the parent post and their comments
  def three_last_comment()
    return self.children.last(3)
  end

  def self.last_news(space)
    return Post.not_events().find(:all, :conditions => {:space_id => space, :parent_id => nil}, :order => "updated_at DESC", :limit => 4)
  end
end

app/controllers/attachments_controller.rb
# -*- coding: utf-8 -*-
# This file is part of Mconf-Web, a web application that provides access
# to the Mconf webconferencing system. Copyright (C) 2010-2012 Mconf
#
# This file is licensed under the Affero General Public License version
# 3 or later. See the LICENSE file.


class AttachmentsController < ApplicationController
  include ActionController::StationResources

  #before_filter :space!
  load_and_authorize_resource :space
  load_and_authorize_resource :attachment, :through => :space

  def index
    attachments
    respond_to do |format|
      format.html
      format.zip{
        generate_and_send_zip
      }
    end
  end

  def edit_tags
    @attachment = Attachment.find(params[:id])
  end

  def delete_collection
    if params[:attachment_ids].blank?
      flash[:error] = "Malformed request"  
      redirect_to space_attachments_path(@space)
    else
      attachments
      errors = ""
      @attachments.each do |attachment|
        if can?(:destroy, attachment)
          attachment.tags.each do |tag|
            tag.delete
          end
          unless attachment.delete
            errors += I18n.t("attachment.error.not_deleted", :file => attachment.filename)
          end
        else
          errors += I18n.t("attachment.error.not_permission", :file => attachment.filename, :user => current_user.username)
        end
      end
      if errors==""
        flash[:success] = I18n.t("attachment.deleted")
      else
        flash[:error] = errors
      end
      
      redirect_to space_attachments_path(@space)
    end
  end

  private

  def attachments
    @attachments,@tags = Attachment.repository_attachments(@space, params)
  end

  # Redirect to spaces/:permalink/attachments if new attachment is created
  def after_create_with_success
    if @attachment.agenda_entry
      redirect_to(space_event_path(@space, @attachment.agenda_entry.event, :show_agenda=>true, :show_day => @attachment.agenda_entry.event_day))
    else
      redirect_to [ space, Attachment.new ]
    end
  end
  
  def after_update_with_success
    redirect_to [ space, Attachment.new ]
  end

  def after_create_with_errors
    flash[:error] =  @attachment.errors.to_xml
    
    if @attachment.agenda_entry
      redirect_to(space_event_path(@space, @attachment.agenda_entry.event, :show_agenda=>true, :show_day => @attachment.agenda_entry.event_day))
    else
      attachments
      render :action => :index
      flash.delete([:error])
    end
  end
 
  def after_update_with_errors
    flash[:error] = @attachment.errors.to_xml
    attachments
    render :action => :index
    flash.delete([:error])
  end
  
  def generate_and_send_zip
    require 'zip/zip'
    require 'zip/zipfilesystem'
  
    t = Tempfile.new("#{@attachments.size}files-#{Time.now.to_f}.zip")
    
    Zip::ZipOutputStream.open(t.path) do |zos|
      @attachments.each do |file|
        zos.put_next_entry(file.filename)
        zos.print IO.read(file.full_filename)
      end
    end

    send_file t.path, :type => 'application/zip', :disposition => 'attachment', :filename => "#{@attachments.size} files from #{@space.name}.zip"
    
    t.close
  end
  
end

app/helpers/attachments_helper.rb
# This file is part of Mconf-Web, a web application that provides access
# to the Mconf webconferencing system. Copyright (C) 2010-2012 Mconf
#
# This file is licensed under the Affero General Public License version
# 3 or later. See the LICENSE file.

module AttachmentsHelper
  def table_actions(row, attachment, interactive)
    #html = ""
    #html << link_to(image_tag("icons/cancel.png", :alt => t('delete'),:class=>"icon"), space_attachment_path(@space,attachment, :version => attachment.version), {:method => :delete, :title => t('attachment.delete'), :confirm => t('delete.confirm', :element => t('attachment.one'))}) if can?(:destroy, attachment)
    #html << link_to("NV")
    #html << link_to(image_tag("icons/comment.png", :alt => t('post.one'),:class=>"icon"), space_post_path(@space,attachment.post)) if attachment.post.present?
    #html << link_to(image_tag("icons/date.png", :alt => t('date.one'),:class=>"icon"), space_event_path(@space,attachment.event)) if attachment.event.present?
    #html

    html=""

    html << if can?(:read, attachment)
              link_to(image_tag("icons/download_doc20.png", :title => t('download'),:class=>"icon"), space_attachment_path(attachment.space,attachment, :format => attachment.format!), :class=>"no-dot")
          else
              image_tag("icons/download_doc20.png", :title => t('login_request' + 'download'),:class=>"icon fade")
            end
    html << if interactive && attachment.current_version? && can?(:update, attachment)
              link_to(image_tag("icons/new_version_doc20.png", :title=> t('version.new'), :class=>"icon"), edit_space_attachment_path(attachment.space, attachment), :class => "repository_sidebar_action no-dot")
            else
              image_tag("icons/new_version_doc20.png", :title=> t('login_request'), :class=>"icon fade")
            end
    html << if interactive && can?(:update, attachment)
              attachment.tags.size>0 ? (link_to(image_tag("icons/pencil.png", :title=> t('tag.edit'),:class=>"icon"),edit_tags_space_attachment_path(attachment.space, attachment), :class=>"repository_sidebar_action no-dot")) : (link_to(image_tag('icons/add_tag20.png', :title => t('tag.add'),:class=>"icon"), edit_tags_space_attachment_path(@space, attachment), :class=>"repository_sidebar_action no-dot"))
            else
              image_tag("icons/pencil.png", :title=>t('login_request' + 'tag.edit'),:class=>"icon fade")
            end

    if can?(:destroy, attachment)
      html << link_to(image_tag("icons/cancel.png", :title => t('delete.one'), :class =>"icon can_delete"), space_attachment_path(attachment.space,attachment), {:method => :delete, :confirm => t('delete.confirm', :element => t('attachment.one'))}, :class=>"no-dot")
      row[:class] += " can_delete"
    else
      html <<  image_tag("icons/cancel.png", :title => t('delete.one'), :class =>"icon fade")
    end

    html.html_safe

  end

  def sortable_header(title,column)
    html = title
    html << " "
    html << link_to(((params[:direction] == 'desc' and column == params[:order]) ? image_tag("down_or.png") : image_tag("down.png")), path_for_attachments({:order => column, :direction => 'desc'}), :class => "sortable table_params desc#{"_active" if (params[:direction] == 'desc' and column == params[:order]) }" )
    html << " "
    html << link_to(((params[:direction] == 'asc' and column == params[:order]) ? image_tag("up_or.png") : image_tag("up.png")), path_for_attachments({:order => column, :direction => 'asc'}), :class => "sortable table_params desc#{"_active" if (params[:direction] == 'asc' and column == params[:order]) }" )
    html.html_safe
  end

  def version_attachment(attachments)

    versioned_attachment_ids = expand_versions_to_array

    att_version_array = attachments.clone

    if versioned_attachment_ids.present?
      versioned_attachment_ids.each do |id|
        if attachments.map(&:version_family_id).include?(id.to_i)
          family = Attachment.version_family(id.to_i)
          attachment = (family & attachments).first
          index = att_version_array.index(attachment)
          att_version_array[index] = family
          att_version_array.flatten!
        end
      end
    end

    att_version_array
  end

  def path_for_attachments(p={})
    direction = p[:direction].present? ? p[:direction] : params[:direction]
    order = p[:order].present? ? p[:order] : params[:order]
    query = p[:query].present? ? p[:query] : params[:query]
    expand_versions=expand_versions_to_array - [p[:not_expanded]] + [p[:expanded]]
    tags = tags_to_array - [p[:rm_tag]] + [p[:add_tag]]
    if @space.nil?
      url_for(:direction => direction, :order => order, :query => query, :expand_versions => expand_versions.uniq.join(","), :tags => tags.uniq.join(","))
    else
      url_for(:space_id => @space,:direction => direction, :order => order, :query => query, :expand_versions => expand_versions.uniq.join(","), :tags => tags.uniq.join(","))
    end

  end

  def options_for_fcbkcomplete(collection,value,text,selected=nil)
    html=""
    collection.each do |t|
      html << %(<option value="#{t.send(value)}"#{"class=selected" if selected.include?(t)}>#{t.send(text)}</option>)
    end
    html
  end

  def attachment_link(attachment, show_filename = true)
    text = show_filename ? truncate(attachment.filename, :length => 28) : t('download_file')
    #link_to text, space_attachment_path(attachment.space,attachment, :format => :all), :title => "#{attachment.filename} (#{attachment.size/1024} kb)"
    link_to text, space_attachment_path(attachment.space,attachment), :title => "#{attachment.filename} (#{attachment.size/1024} kb)"
  end

  private

  def expand_versions_to_array
    params[:expand_versions].present? ? params[:expand_versions].split(",").map(&:to_i) : Array.new
  end

  def tags_to_array
    params[:tags].present? ? params[:tags].split(",").map(&:to_i) : Array.new
  end

  def tags_list tag_array
    html = "<ul class=\"holder\">"
    tag_array.each do |tag|
      html << "<li class=\"w-cross\">#{tag.name}</li>"
    end
    html << "</ul>"
  end

  def tag_count(elements, less=[], p={})
    order = p[:order] || "popularity"

    tags_with_duplicates = elements.map(&:tags).flatten.compact - less

    #Count elements
    count = Hash.new(0)
    tags_with_duplicates.each do |tag|
      count[tag] += 1
    end

    case order
    when "abc"
      count.keys.sort{|x,y| x.name <=> y.name }.map{|t| {:tag=> t, :count => count[t]}}
    else
      count.keys.sort{|x,y| count[y] <=> count[x]}.map{|t| {:tag=> t, :count => count[t]}}
    end

  end
end

app/views/attachments/_attachment.html.erb
<%= form.file_field :uploaded_data, :class => "file_1" %>

app/views/attachments/_author_box.html.erb
<%=link_to object.author.name, user_path(object.author)%>

app/views/attachments/_comment.erb
<% rounded(:class => "tips") do %>
<%user = User.find(comment.agent_id)%>
comment created at <%= comment.created_at.strftime("%d-%m-%Y") %>  by <%= user.login unless user.profile%><%= user.profile.name if user.profile%> <%= user.profile.lastname if user.profile%><br>
<b><%= sanitize comment.title%></b><br />
<%= sanitize comment.description %>
<%= render :partial =>'attachments/attachment' , :locals => {:entry => comment}%>
<% end -%>

app/views/attachments/_edit_tags_form.html.erb
<div id="doc_action" class="edit_tags">
	<h3><%=t("tag.edit")%></h3>
	<div class="doc_action_content">
	<%= form_for prepare_for_form(@attachment), :html => { :multipart => true, :method => :put} do |f|%>
		<%=hidden_field_tag 'format', 'html'%>
	  <span class="bold"><%=t('attachment.file')%></span> <span><%=@attachment.filename%></span>
		<div class="margin-up"><span class="bold"><%=t('tags')%>:</span></div>
		<input id="attachment_tags" type="hidden" value="" name="attachment[_tags][]"/>
    <select id="attachment_edit_tags" multiple="multiple" name="attachment[_tags][]">
      <%=options_for_select_with_class_selected(@space.tags.map{|t| t.name }, attachment.tags.map{|t| t.name}).html_safe%>
		</select>
	  <div class="margin-up"><button class="basic_button blue_button" type="submit"><%=t("button.update")%></button></div>
	<%end%>
	</div>
</div>

app/views/attachments/_form.erb
  <!--las 3 líneas del if mirar con más detalle si son prescindibles  -->
  <p>
	<%if @content.id != nil%>
	<%@entry = Entry.find(:first , :conditions => {:content_id => @content.id,:content_type => "Attachment"})%>
	<%end%>
	
    <b>Text</b><br />
<%= fckeditor_textarea(:entry, :description, :toolbarSet => 'Simple', :width => '685px', :height => '400px') %> 
 <%= render :partial => 'attachments/attach' %>
 <div>
 <%content_type = get_attachment_content_type(@entry)%>
<%image = get_attachment_image(content_type)%>
	<p>Attachment:<%= image_tag(image)%><%=@entry.content.size/1024%> Kb</p>
 </div>
    </p>

app/views/attachments/_repository_filter.js.erb
  // Global variables
	
	  //in mixed filter
	filtered_title = null;
	filtered_author = null;
	filtered_type = null;
	filtered_any = null;
	
	  //in event filter
	filtered_event = null;
	
	// Show attachments according to global filtered_* variables
  filter_attachments = function(){
	  $("tr.ui-collection-result").each(function() {
		  if(
			  (filtered_title==null  || $(this).children("td.attachment-name").children("a").text().toLowerCase().search(filtered_title.toLowerCase())>=0) &&
			  (filtered_author==null || $(this).children("td.attachment-author").children("a").text().toLowerCase().search(filtered_author.toLowerCase())>=0) &&
				(filtered_type==null   || $(this).children("td.attachment-name").attr("rel")==filtered_type) &&
				(filtered_any==null    || $(this).children("td.attachment-name").children("a").text().toLowerCase().search(filtered_any.toLowerCase())>=0
                               || $(this).children("td.attachment-author").children("a").text().toLowerCase().search(filtered_any.toLowerCase())>=0)&&
				(filtered_event==null  || $(this).attr("rel")==filtered_event)
        )
      {
        $(this).css("display","");
      }
      else{
        $(this).hide();
      }
		});
	}
	
	
	//Mixed filter event listeners
	
	$("#title_filter").livequery('keyup', function() {
    filtered_title=this.value;
    filter_attachments();
  });
  
  $("#author_filter").livequery('keyup', function() {
    filtered_author=this.value;
    filter_attachments();
  });
  
  $("#any_field_filter").livequery('keyup', function() {
    filtered_any=this.value;
    filter_attachments();
  });
  
  $("#type_filter").livequery('change', function() {
    filtered_type = $(this).val()=="" ? null : $(this).val();
    filter_attachments();
  });
  
  $("#mix_filter").livequery('change', function() {
    filtered_title = null;
    filtered_author = null;
    filtered_type = null;
    filtered_any = null;
    
    $(".mixed_alternative").hide();
    $("#" + $(this).val()).val("").show();
    
    filter_attachments();
    
  });

	
	//Event filter event listener
	
  
  $("#event_select").livequery('change', function() {
    filtered_event = $(this).val()=="" ? null : "event_" + $(this).val();
    filter_attachments();
  });
  

app/views/attachments/_repository_javascript.js.erb
//Upload form
$("input#add_post").livequery("click",function(){
  $("#with_post").slideToggle();
});

$("#add_document_label_link").click(function() {
  $("#new_attachment").effect("highlight", {color:"#F5DF51"}, 3000);
});

$("#attachment__tags").fcbkcomplete({
    cache: true,
          filter_case: false,
          filter_hide: true,
          firstselected: true,
          filter_selected: true,
          maxshownitems: 4,
          newel: true,
          complete_opts: true
  });

// Action links
$("a.repository_sidebar_action").livequery("click",function(){
  if($(this).hasClass("disabled_button")){
    return false;
  }else{
    collapse_tag_list();
    $.getScript(this.href);
    return false;
  }
});

//Multiple selectors actions

selected_attachments = function(){
  var sa = new Array();
  $(".attachment_checkbox").each(function(){
    if($(this).attr('checked')){
      sa.push($(this).attr("value"));
    }
  });
  return sa;
};

can_delete_selected = function(){
  var can_delete = true
  $(".attachment_checkbox:checked").each(function(){
    if(!$(this).parents("tr.attachment").hasClass("can_delete")){
      can_delete = false;
    }
  });
  return can_delete;
};

update_selected = function(){
  var sa = selected_attachments();
  if(sa.length==0){
    $("#selected_info").html("<%=escape_javascript(t('attachment.selected.none'))%>");
    $("#multiple_download").addClass("disabled_button");
    $("#multiple_delete").addClass("disabled_button");
  }else{
    if(sa.length==1){
      $("#selected_info").html(sa.length + "<%=escape_javascript(t('attachment.selected.one'))%>");
    }else{
      $("#selected_info").html(sa.length + "<%=escape_javascript(t('attachment.selected.other'))%>");
    }
    $("#multiple_download").removeClass("disabled_button");
    //Check permissions
    if(can_delete_selected()){
      $("#multiple_delete").removeClass("disabled_button");
    }else{
      $("#multiple_delete").addClass("disabled_button");
    }
  }
}

$(".attachment_checkbox").click(function(){
  update_selected();
});

$("#select_all_checkbox").click(function(){
  if($(this).attr("checked")){
    $(".attachment_checkbox").attr("checked", true);
  }else{
    $(".attachment_checkbox").attr("checked", false);
  }
  update_selected();
});

$("#multiple_download").click(function(){
  if($(this).hasClass("disabled_button")){
    return false;
  }else{
    var sa = selected_attachments();
    $(this).attr("href", "<%=space_attachments_path(@space, :format => "zip")%>" + "?attachment_ids=" + sa.join(","));
  }
});

$("#multiple_delete").click(function(){
  if($(this).hasClass("disabled_button")){
    return false;
  }else{
    if(confirm('Delete selected attachments?')){
      var sa = selected_attachments();
      var f = document.createElement('form');
      f.style.display = 'none';
      this.parentNode.appendChild(f);
      f.method = 'POST';
      f.action = "<%=space_attachments_path(@space)%>" + "?attachment_ids=" + sa.join(",");
      var m = document.createElement('input');
      m.setAttribute('type', 'hidden');
      m.setAttribute('name', '_method');
      m.setAttribute('value', 'delete');
      f.appendChild(m);
      var s = document.createElement('input');
      s.setAttribute('type', 'hidden');
      s.setAttribute('name', 'authenticity_token');
      s.setAttribute('value', '<%=form_authenticity_token()%>');
      f.appendChild(s);
      f.submit();
    }
    return false;
  }
});

//Initial actions
$("#enable_javascript").hide();
update_selected();

app/views/attachments/_unified_attachment.html.haml
= div_for(attachment, :class => "thread thread-attachment #{cycle("thread-even" , "thread-odd")}") do

  .logo-in-thread
    = link_logo(attachment.space, :size => 'w48', :url => space_path(attachment.space), :title => attachment.space.name).html_safe

  .thread-content

    %ul.thread-action-links.visible-on-hover{ :"data-hover-tracked" => "attachment_#{attachment.id}" }
      - if can?(:destroy, attachment)
        %li= link_to t('remove').downcase, space_attachment_path(attachment.space, attachment), {:method => :delete, :title => t('delete.one'), :confirm => t('delete.confirm', :element => attachment.filename) }

    .thread-title
      = attachment_icon t('attachment.home.one', :space => attachment.space.name)
      = link_to sanitize(attachment.filename), space_attachment_path(attachment.space, attachment, :format => attachment.format!)
      %span.thread-updated-at= t('created_time_ago', :time => sanitize(time_ago_in_words(attachment.created_at)))

    %span= t('author') + ":"
    = link_to attachment.author.name,user_path(attachment.author)

app/views/attachments/_upload_form.html.erb
<script type="text/javascript">
  $(document).ready(function(){
    if($("#upload_field").value != null){
      $("#button_submit").show();
    }
  });

  $("#upload_field").livequery("change", function(){
      $("#button_submit").show();
  });
</script>

<%if can?(:create_attachment, @space)%>
  <div id="doc_action">
    <div id="add_new_doc">
      <h3 class="blue"><%=t("document.upload")%></h3>
      <%= form_for(prepare_for_form(@attachment || Attachment.new), :html => { :multipart => true}) do |f|%>
        <div class="new_doc_content">
          <div id="cabinet">
            <%= f.file_field :uploaded_data, :id=>"upload_field", :class=>"file_1", :size=>"15"%>
          </div>
        </div>
        <div class="new_doc_content">
          <span class="bold"><%=t('tag.new')%> <%=image_tag("icons/help.png",:title=>t("tooltip.tag"),:size=>"16x16",:class=>"icon tooltipped upwards",:style=>"cursor:pointer")%></h3></span>
          <div id=tags>
            <%= select(:attachment, :_tags, @space.tags.map{|u| u.name}, {}, {:multiple=>"multiple"})%>
          </div>
        </div>
        <div class="new_doc_content">
          <span><%= check_box_tag "add_post", "with_post", attachment.post_title.present? || attachment.post_text.present?%> <%=t('attachment.upload_with_post')%></span>
          <div id="with_post" <%="style=\"display:none\"".html_safe if !(attachment.post_title.present? || attachment.post_text.present?)%>>
            <%= f.label :post_title, t('title') %><br/>
            <%= f.text_field :post_title%>
            <%= f.label :post_text, t('text') %><br/>
            <%= f.text_area :post_text, :rows => 5, :cols=>25%>
          </div>
          <div class="margin-up" id="button_submit" style="display:none">
            <button type="submit" class="basic_button blue_button"><%=t("button.upload")%></button>
          </div>
        </div>
      <%end%>
    </div>
  </div>
<%end%>

app/views/attachments/edit.js.erb
$("div#doc_action").replaceWith("<%=escape_javascript(render(:partial => 'new_version_form', :locals => {:attachment => @attachment}))%>");
$("#attachment_new_version_tags").fcbkcomplete({
	cache: true,
  filter_case: false,
  filter_hide: false,
  firstselected: true,
  filter_selected: true,
  maxshownitems: 4,
	newel: true     
});

app/views/attachments/edit_tags.js.erb
$("#doc_action").replaceWith("<%=escape_javascript(render(:partial => 'edit_tags_form'))%>");
$("#attachment_edit_tags").fcbkcomplete({
  cache: true,
  filter_case: false,
  filter_hide: false,
  firstselected: true,
  filter_selected: true,
  maxshownitems: 4,
  newel: true
});