config/routes.rb
Mconf::Application.routes.draw do

  controllers = { :sessions => "sessions", :registrations => "registrations" }
  paths = { :sign_in => "login", :sign_out => "logout", :sign_up => "signup" }
  devise_for :users, :path_names => paths, :controllers => controllers
  devise_scope :user do
    get "login", :to => "sessions#new"
    get "logout", :to => "sessions#destroy"
    get "register", :to => "registrations#new"
  end

  bigbluebutton_routes :default, :controllers => { :servers => 'custom_bigbluebutton_servers', :rooms => 'custom_bigbluebutton_rooms' }

  match '/webconf/:id', :to => 'custom_bigbluebutton_rooms#invite',
                        :as => "join_webconf"

  match '/secure', :to => 'shibboleth#create', :as => "shibboleth"
  match '/secure/info', :to => 'shibboleth#info', :as => "shibboleth_info"

  resources :logos do
    collection do
      post :new
    end
  end

  resources :machines do
    collection do
      get :contact_mail
      get :my_mailer
    end
  end

  resources :spaces do

    bigbluebutton_routes :room_matchers

    member do
      post :enable
      post :leave
    end

    resources :users do
      resource :profile, :except => [:new, :create]
    end

    resource :webconference
    resources :readers

    resources :events do

      member do
        post :spam
        get :spam_lightbox
      end

      collection do
        get :add_time
        get :copy_next_week
        get :remove_time
      end

      resources :invitations
      resources :participants

      resource :logo, :controller => 'event_logos' do
        member do
          post :precrop
        end
      end
    end

    resources :posts do
      member do
        get :reply_post
        post :spam
        get :spam_lightbox
      end
    end

    delete 'attachments', :to => 'attachments#delete_collection', :as => 'attachments'

    resources :attachments do
      member do
        get :edit_tags
      end
    end

    resources :entries
    resource :logo do
      member do
        post :new
        post :precrop
      end
    end

    resources :admissions
    resources :invitations
    resources :join_requests
    resources :news
  end

  resources :invitations do
    member do
      get :accept
    end
  end

  resources :permissions
  resources :admissions
  resources :memberships

  resources :users do
    get :fellows, :on => :collection, :defaults => { :format => 'json' }
    get :select_users, :on => :collection
    get :current, :on => :collection, :defaults => { :format => 'xml' }
    member do
      post :enable
      get :edit_bbb_room
    end

    resources :private_messages, :as => 'messages', :except => [:edit]
    resource :profile, :except => [:new, :create] do
      resource :logo
    end
    resource :avatar do
      member do
        post :precrop
      end
    end
  end

  resource :home do
    member do
      get :user_rooms
    end
  end

  resource :invite do
    member do
      get :invite_room, :as => 'inviteroom'
      post :send_invite, :as => 'sendinvite'
      get :send_notification, :as => 'sendnotification'
    end
  end

  resources :feedback do
    collection do
      get :webconf
    end
  end

  resource :site, :only => [:show, :edit, :update]

  match '/manage/users', :to => 'manage#users', :as => 'manage_users'
  match '/manage/spaces', :to => 'manage#spaces', :as => 'manage_spaces'
  match '/manage/spam', :to => 'manage#spam', :as => 'manage_spam'

  resource :session_locale
  match ':locale/:controller/:action/:id'
  match 'locale/set/:id', :to => 'locale#set', :as => 'set'

  root :to => 'frontpage#show'

  match 'help', :to => 'faq#show', :as => 'help'
  match 'faq', :to => 'faq#show', :as => 'faq'

  match '/statistics', :to => 'statistics#show', :as => 'show_statistics'

  match '/reset_password/:reset_password_code', :to => 'users#reset_password', :as => 'reset_password'

  match 'get_file/:id', :to => 'machines#get_file', :as => 'get_file'

  unless Rails.application.config.consider_all_requests_local
    match '*not_found', :to => 'errors#error_404'
  end
end

app/controllers/frontpage_controller.rb
# -*- coding: utf-8 -*-
# This file is part of Mconf-Web, a web application that provides access
# to the Mconf webconferencing system. Copyright (C) 2010-2012 Mconf
#
# This file is licensed under the Affero General Public License version
# 3 or later. See the LICENSE file.

class FrontpageController < ApplicationController

  layout 'clean'

  def show
    # @relevant_users = User.find(:all).sort_by{|user| user.posts.size}.reverse.first(4)
    # @recent_spaces = Space.find(:all, :conditions => {:public => true},:order => "created_at Desc").first(3)
    # @recent_events = Event.find(:all, :order => "start_date Desc").select{|p| !p.space.disabled? && p.space.public? &&  p.start_date && p.start_date.future?}.first(2)
    # @recent_posts = Post.find(:all, :conditions => {:parent_id => nil}, :order => "created_at Desc").select{|p| !p.space.disabled? && p.space.public == true}.first(2)
    # @recent_spaces = Space.where(:public => true).order("created_at Desc").first(4)

    # Find the public spaces that have most pageviews
    # @most_active_spaces = []
    # Statistic.where(['url LIKE ?', '/spaces/%']).order('unique_pageviews desc').each do |rec|
    #   perma = rec.url.split("/").last
    #   space = Space.find_by_permalink(perma)
    #   @most_active_spaces << space if space and space.public?
    #   break if @most_active_spaces.size == 10
    # end

   respond_to do |format|
      if user_signed_in?
        format.html { redirect_to home_path }
      else
        format.html
      end
    end
  end

end

app/helpers/frontpage_helper.rb
# This file is part of Mconf-Web, a web application that provides access
# to the Mconf webconferencing system. Copyright (C) 2010-2012 Mconf
#
# This file is licensed under the Affero General Public License version
# 3 or later. See the LICENSE file.

module FrontpageHelper

  # Methods needed to include devise's forms in the frontpage'
  def resource_name
    :user
  end
  def resource
    @resource ||= User.new
  end
  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

end

app/views/frontpage/_global_header.html.haml
#global-header

  #main-logo
    %a.title{:href => root_path}= t('mconf')
    %span.subtitle .org

  #registration-box
    %span= t('frontpage.register_sentence')
    .register_button
      %a.button.orange.big{:href => signup_path}= t('register.one')

  #login-box
    = t('login.login_desc')
    = simple_form_for :session, :url => session_url(:protocol => current_site.protocol) do |f|
      = f.text_field :login
      = f.label t('login.email_or_login')
      = f.password_field :password
      = f.label t('login.password')
      = f.button :submit, t("login.one")
    .action-links
      = link_to t('user.lost_password'), lost_password_path
      - if current_site.shib_enabled?
        = link_to t('cafe.login'), shibboleth_path, :class => 'shibboleth_login'

app/views/frontpage/_space_list.html.erb
<ul>
  <% spaces.each do |space| %>
    <% room = space.bigbluebutton_room %>
    <li>
      <div class="space_container">
        <h3><a href="<%=space_path(space)%>"> <%= space.name %> </a></h3>
        <a href="<%=space_path(space)%>"><%= logo(space, :size=> 'h64', :title => sanitize(space.name)).html_safe %></a>
        <div class="space_info">
          <h4><%= t('frontpage.about') %></h4>
          <ul>
            <li>
              <%=space.users.count%> <%=t('frontpage.members')%>
            </li>
            <li>
              <a href="<%=space_path(space)%>"><%=t('frontpage.more_info')%></a>
            </li>
          </ul>
        </div>
        <div class="space_webconference">
          <% count = (room.participant_count.nil?) ? 0 : room.participant_count %>
          <% if room.is_running? %>
            <div class="join_button">
              <a href="<%= invite_space_room_path(space, room) %>"><span><%=t('frontpage.join_button')%></span></a>
            </div>
          <% end %>
          <h4><%= t('webconference.one') %></h4>
          <span <%= 'class="active"'.html_safe if room.is_running? %>><%= room.is_running? ? t('frontpage.running', :count => count) : t('frontpage.not_running') %></span>
        </div>
        <div class="clearer">&nbsp;</div>
      </div>
    </li>
  <% end %>
</ul>

app/views/frontpage/about2.html.erb
 <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN"
  "http://www.w3.org/TR/html4/strict.dtd">

<html lang="en">
  <head>
    <meta http-equiv="Content-type" content="text/html; charset=utf-8">
    <title></title>
    <link href="/favicon.ico" rel="shortcut icon" />

  <link href="stylesheets/about.css" media="screen, projection" rel="stylesheet" type="text/css" />
  <link href="stylesheets/print.css" media="print" rel="stylesheet" type="text/css" />

  <link rel="stylesheet" href="stylesheets/galleriffic.css" type="text/css" />
    <%= javascript_include_tag 'jquery', 'application', 'jquery.livequery', 'jquery.fancybox', 'jquery.easing', 'jquery-ui', 'jquery.form' %>
    <%= javascript_include_tag 'jquery.galleriffic.js'%>

    <!--[if IE]>
    <link href="stylesheets/ie.css?1242919478" media="screen, projection" rel="stylesheet" type="text/css" />
    <![endif]-->

  </head>

  <body>
  <div id="site">
    <div id="home">
      <div id="header">
        <div id="logo">
                  <img alt="Gp-logo" height="80" src="images/gp-logo.jpg" width="80" />
                </div>

                <div id="search">
                  <h1>ABOUT GLOBAL</h1>
                </div>

                <%= render :partial => 'layouts/header_logo' %>

      </div>

          <div id="content">
        <div id="main">
          <div class="about-wrapper">
            <h3 class="title">GLOBAL Description</h3>
            <div id="description">
                      <p>
                        Global Linkage Over BroadbAnd Links will provide a virtual conference centre using advanced communication technologies and concepts to support the promotion of e-infrastructure topics in Europe and around the world.
                      </p>
                      <p>
                        One main goal of GLOBAL will be to allow and help research projects to disseminate their results and training events to a wider audience located in multiple geographical locations through the organization of virtual conferences. GLOBAL will provide a user-centric interface for planning, creation, announcement, coordination, content management and realisation of virtual conferences with open and wide participation. Through these virtual conferences the participating users will be able to exchange information on e-infrastructure development in their region, identify partners for future collaboration and exchange and discuss synergies between their running initiatives.
                      </p>
                      <p>
                        The virtual conference events will provide advanced videoconferencing and collaboration tools and support to the participants. Each event will be recorded and stored on a repository together with documents and outcomes for future consultation. The virtual conference centre will provide three main functions focused on usability: a virtual auditorium, for planning, coordination and management of the virtual events, an event repository, to store the recordings and outcomes of the events, and a virtual corridor, which will support networking and partnership building amongst the participants.
                      </p>
                      <p>
                        The project is supported by the European Commissions/ 7 FRAMEWORK PROGRAMME/THEME Capacities/Research Infrastructures.
                      </p>
                    </div>
          </div>
         </div>

                <div id="sidebar">
                  <div id="about-sidebar">
                        <div id="go-vcc">
                          <img alt="Vcc-logo" src="images/vcc-logo1.png" title="Virtual Conference Centre" />
                          <button type="button" onclick="location.href='http://vcc.dit.upm.es'"><%= image_tag("bola_global_peque.png",:class=>"icon")%> Go to Virtual Conference Centre</button>
                        </div>
                        <br/>

                        <div class="partners">
                        <h5>Partners</h5>
                          <div>
                                <ul>
                                  <li><a href="http://www.zsi.at/">Zentrum für Soziale Innovation (ZSI)</a></li>
                                  <li>Austria</li>
                                </ul>
                                <ul>
                                  <li><a href="http://www2.upm.es/institucional">U. Politécnica de Madrid (UPM)</a></li>
                                  <li>Spain</li>
                                </ul>
                                <ul>
                                  <li><a href="http://www.agora-2000.com/">Agora Systems S.A. (ASSA)</a></li>
                                  <li>Spain</li>
                                </ul>
                                <ul>
                                  <li><a href="http://www.redclara.net/">Cooperación Latino Americana de Redes Avanzadas (CLARA)</a></li>
                                  <li>Uruguay</li>
                                </ul>
                                <ul>
                                  <li><a href="http://www.ucl.ac.uk/">University College London (UCL)</a></li>
                                  <li>United Kingdom</li>
                                </ul>
                                <ul>
                                  <li><a href="http://www.ijs.si/ijsw/JSI">Jozef Stefan Institute (JSI)</a></li>
                                  <li>Slovenia</li>
                                </ul>
                                <ul>
                                  <li><a href="http://www.ubuntunet.net/">Ubuntunet (Ubuntunet)</a></li>
                                  <li>Malawi</li>
                                </ul>
                          </div>
                        </div>

                        <div class="contact">
                          <h5><%= t('contact_information') %></h5>
                          <ul>
                                <li>Margit Hofer</li>
                                <li>Zentrum für Soziale Innovation</li>
                                <li>Linke Wienzeile 246</li>
                                <li>1150 Wien</li>
                                <li><%= t('e-mail.one') %>: hofer@zsi.at</li>
                                <li><%= t('phone') %>: +43/ 1 495 04 42 -  63</li>
                          </ul>
                        </div>
                  </div>
                </div>
      </div>
          <div id="footer">
            <ul>
              <li id="trade_mark"><img alt="Bola_global_peque" class="icon" src="/images/bola_global_peque.png?1242226208" /> global-project.eu</li>
              <li>-</li>
              <li><%= t('all_rights_reserved') %></li>
            </ul>
          </div>
    </div>

  </div>
  <script type="text/javascript">
                        // We only want these styles applied when javascript is enabled
                        $('div.navigation').css({'width' : '506px', 'float' : 'left','padding' : '0 10px 10px 10px', 'margin' : '0 22px'});
                        $('div.content').css('display', 'block');

                        // Initially set opacity on thumbs and add
                        // additional styling for hover effect on thumbs
                        var onMouseOutOpacity = 0.67;
                        $('#thumbs ul.thumbs li').css('opacity', onMouseOutOpacity)
                                .hover(
                                        function () {
                                                $(this).not('.selected').fadeTo('fast', 1.0);
                                        },
                                        function () {
                                                $(this).not('.selected').fadeTo('fast', onMouseOutOpacity);
                                        }
                                );

                        $(document).ready(function() {
                                // Initialize Advanced Galleriffic Gallery
                                var galleryAdv = $('#gallery').galleriffic('#thumbs', {
                                        delay:                  2000,
                                        numThumbs:              8,
                                        preloadAhead:           8,
                                        enableTopPager:         false,
                                        enableBottomPager:      true,
                                        imageContainerSel:      '#slideshow',
                                        controlsContainerSel:   '#controls',
                                        captionContainerSel:    '#caption',
                                        loadingContainerSel:    '#loading',
                                        renderSSControls:       true,
                                        renderNavControls:      true,
                                        playLinkText:           'Play Slideshow',
                                        pauseLinkText:          'Pause Slideshow',
                                        prevLinkText:           '&lsaquo; Previous Photo',
                                        nextLinkText:           'Next Photo &rsaquo;',
                                        nextPageLinkText:       'Next &rsaquo;',
                                        prevPageLinkText:       '&lsaquo; Prev',
                                        enableHistory:          false,
                                        autoStart:              false,
                                        onChange:               function(prevIndex, nextIndex) {
                                                $('#thumbs ul.thumbs').children()
                                                        .eq(prevIndex).fadeTo('fast', onMouseOutOpacity).end()
                                                        .eq(nextIndex).fadeTo('fast', 1.0);
                                        },
                                        onTransitionOut:        function(callback) {
                                                $('#caption').fadeOut('fast');
                                                $('#slideshow').fadeOut('fast', callback);
                                        },
                                        onTransitionIn:         function() {
                                                $('#slideshow, #caption').fadeIn('fast');
                                        },
                                        onPageTransitionOut:    function(callback) {
                                                $('#thumbs ul.thumbs').fadeOut('fast', callback);
                                        },
                                        onPageTransitionIn:     function() {
                                                $('#thumbs ul.thumbs').fadeIn('fast');
                                        }
                                });
                        });
        </script>
  </body>
</html>

app/views/frontpage/index.html.haml
- content_for :"global-header" do
  = render :partial => "global_header"

#page-header
  #page-header-content
    .headline= t('frontpage.project_description').html_safe
    .links
      %ul
        %li
          %a.link-title{:href => "http://inf.ufrgs.br/prav/gtmconf"}= t('frontpage.links.project_website')
          %br/
          %span.link-description= t('frontpage.links.project_website_desc')
        %li
          %a.link-title{:href => "https://github.com/mconf"}= t('frontpage.links.source_code')
          %br/
          %span.link-description= t('frontpage.links.source_code_desc')
        %li
          %a.link-title{:href => "http://code.google.com/p/mconf"}= t('frontpage.links.docs')
          %br/
          %span.link-description= t('frontpage.links.docs_desc')

#content-mconf
  = render :partial => "components"
  #content-searching-for
    .section-title
      %h2= t('frontpage.searching_for.title')
    .content-block
      = image_tag('frontpage/icon-use-pb-40x40.png', :size => '40x40')
      .text
        %span.link-title
          %a{:href => signup_path}= t('frontpage.searching_for.use.title')
        %span= t('frontpage.searching_for.use.message').html_safe
    .content-block
      = image_tag('frontpage/icon-install-pb-40x40.png', :size => '40x40')
      .text
        %span.link-title
          %a{:href => "http://code.google.com/p/mconf/wiki/MconfInstallation"}= t('frontpage.searching_for.install.title')
        %span= t('frontpage.searching_for.install.message').html_safe
    .content-block
      = image_tag('frontpage/icon-collaborate-pb-40x40.png', :size => '40x40')
      .text
        %span.link-title
          %a{:href => "http://code.google.com/p/mconf/wiki/MconfCollaborate"}= t('frontpage.searching_for.collaborate.title')
        %span= t('frontpage.searching_for.collaborate.message').html_safe
    = render_clearer
  = render_clearer

#content-current-site
  = render :partial => 'space_list', :locals => { :spaces => @most_active_spaces }
  = render_clearer

app/views/frontpage/performance.html.erb
 <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN"
  "http://www.w3.org/TR/html4/strict.dtd">

<html lang="en">
  <head>
    <meta http-equiv="Content-type" content="text/html; charset=utf-8">
    <title>Performance throughout the project duration</title>
    <link href="/favicon.ico" rel="shortcut icon" />

  <link href="stylesheets/about.css" media="screen, projection" rel="stylesheet" type="text/css" />
  <link href="stylesheets/print.css" media="print" rel="stylesheet" type="text/css" />

  <!--[if IE]>
  <link href="stylesheets/ie.css?1242919478" media="screen, projection" rel="stylesheet" type="text/css" />
  <![endif]-->

  </head>

  <body>
        <div id="site">
    <div id="home">
      <div id="header">
        <div id="logo">
                  <img alt="Gp-logo" height="80" src="images/gp-logo.jpg" width="80" />
                </div>

                <div id="search">
                  <h1>Performance throughout the project duration</h1>
                </div>

                <%= render :partial => 'layouts/header_logo' %>

      </div>

          <div id="content">
        <div id="main">
        <%= link_to "<span>Back to GLOBAL webpage</span>", "http://global-project.eu", :class => "with_margin_down new_space_link big_button orange_button"%>
                <br/>
        <div class="perf_message">
                *All these graphs present cumulative data up to the end of the project in November 2010
        </div>

        <%= image_tag("demo/Imagen1.png",:class=>"performance_imagen") %>
                <div class="imagen_explanation"><span class="explanation_tilte">GlobalPlaza Communities: </span> This graph shows the number of <i>spaces</i> created by registered users since the release in April 2009. Not all GlobalPlaza users create their own community. Nevertheless, it is necessary to create a space in order to organise a virtual event. The number of communities losely corresponds with the number of performed events.</div>
                <div class="greyRule"></div>
                <%= image_tag("demo/Imagen3.png",:class=>"performance_imagen") %>
                <div class="imagen_explanation"><span class="explanation_tilte">GlobalPlaza Events: </span> This graph shows the number of Events organised through the GlobalPlaza site since the release in April 2009, both public (open to everybody) and private events (restricted to members of a specific community). Events are usually organised in a GlobalPlaza Space to target a specific community. So an increase in communities is reflected in the increase in created events.The numbers shown here include events in private spaces. A search via GlobalPlaza will most likely show a different number because it only yields results for spaces a user has access to. </div>
                <div class="greyRule"></div>
                <%= image_tag("demo/Imagen5.png",:class=>"performance_imagen") %>
                <div class="imagen_explanation"><span class="explanation_tilte">GlobalPlaza Users: </span> This graph shows the number of users registered on the GlobalPlaza site since the release in April 2009. Users register if they want to participate actively. The number of new registrations seems to correspond with the number of events (see below) which act as a driver for new users to join.</div>
                <div class="greyRule"></div>
                <%= image_tag("demo/Imagen7.png",:class=>"performance_imagen") %>
                <div class="imagen_explanation"><span class="explanation_tilte">GlobalPlaza Messages: </span>This graph shows the number of Messages on the Wall of the different Spaces since the release in April 2009. The number of messages depend on the activity of the different Spaces. </div>
                <div class="greyRule"></div>
                <%= image_tag("demo/Imagen9.png",:class=>"performance_imagen") %>
                <div class="imagen_explanation"><span class="explanation_tilte">GlobalPlaza Videos: </span> This graph shows the number of videos recorded by the GlobalPlaza service for the events organised since the release in April 2009. User can choose whether or not they want to record their event. Although the number of events and the number of recorded videos seem to correlate they do not. Also, the events are not all of the same size; some have just one recording, some are full-fledged events with many sessions and breaks with more than one day duration in which each session is recorded separately. These big events are usually created far in advance. The respective videos may be recorded by different means and published some time later.</div>
                <div class="greyRule"></div>
                <%= image_tag("demo/Imagen11.png",:class=>"performance_imagen") %>
                <div class="perf_message">
                *The next graph present monthly data (not cumulative)
        </div>
                <%= image_tag("demo/Imagen13.png",:class=>"performance_imagen") %>
                <div class="imagen_explanation"><span class="explanation_tilte">GlobalPlaza Unique Visitors: </span>This graph shows the number of unique visitors to the GlobalPlaza site since December 2009. We present this data in a cumulative and non-cumulative graphs. In general the highest monthly number of Unique Visitors coincide with an increase in User registrations and the creation of events. The number of unique visitors can be correlated to the number of events at the early months, but later these visitors will not only attend or view event dissemination information but also available recordings.</div>

                <%= link_to "<span>Back to GLOBAL webpage</span>", "http://global-project.eu", :class => "new_space_link big_button orange_button"%>
                </div>
          </div>
    </div>
  </div>

  </body>
</html>

app/views/frontpage/show.html.haml
- content_for :navbar do
  #navbar
    #main-logo
      %a.title{:href => root_path}= image_tag 'logos/mconf-white-transp.png', :size => '231x120'

- content_for :page_header do
  = t("frontpage.headline")

#content

  #login-box.form-area
    %h2= t('login.login_desc')
    = render :partial => 'sessions/login_form'
    .action-links
      %ul
        %li= link_to t('user.lost_password'), new_user_password_path
        %li= link_to t("user.resend_confirmation_email.link"), new_confirmation_path(resource_name)
        - if current_site.shib_enabled?
          %li= link_to t('cafe.login'), shibboleth_path, :class => 'shibboleth_login'

  #registration-box.form-area
    %h2= t('register.one')
    = render :partial => 'registrations/signup_form'